# Generated by Django 6.0 on 2025-12-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OilField',
            fields=[
                ('oil_field', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=512)),
                ('operator_company', models.CharField(max_length=256)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('pressure', 'Pressure'), ('temperature', 'Temperature'), ('flow_rate', 'Flow Rate')], max_length=20)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionReading',
            fields=[
                ('reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='resources.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('well_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('drill_date', models.DateField(blank=True, null=True)),
                ('depth_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('shut-in', 'Shut-In'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('oil_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='resources.oilfield')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='resources.well'),
        ),
    ]
