# Generated by Django 6.0 on 2025-12-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oilfield',
            old_name='oil_field',
            new_name='oil_field_id',
        ),
    ]
